[tool.poetry]
name = "4900rl"
version = "0.0.1"
description = ""
authors = [
    "Anthony Y. Zhu <anthonyzhu@cmail.carleton.ca>"
]
license = "MIT"
readme = "README.md"
packages = [
  {include = "playground", from = "src"},
  {include = "project", from = "src"}
]

[tool.poetry.scripts]
playground = "src.playground.main:run"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.24.1"
gymnasium = "^0.29.1"
box2d-py = "^2.3.8"
pygame = "^2.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"